In [1]:
import numpy as np

# 1. Import numpy as np and see the version


In [2]:
np.__version__

'1.14.1'

# 2. How to create a 1D array?

In [3]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?


In [8]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?


In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]

array([1, 3, 5, 7, 9])

# 5. How to replace items that satisfy a condition with another value in numpy array?

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = np.where(arr%2 ==1,-1,arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 7. How to reshape an array?

In [27]:
arr=np.arange(10)

arr=arr.reshape(2,5) #arr.reshape(2, -1) 
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8. How to stack two arrays vertically?

In [30]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

arr = a+b
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9. How to stack two arrays horizontally?


In [34]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.c_[a, b]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [35]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. How to generate custom sequences in numpy without hardcoding?

In [37]:
a = np.array([1,2,3])



np.r_[np.repeat(a, 3), np.tile(a, 3)]



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)
#> array([2, 4])

array([2, 4])

# 12. How to remove from one array those items that exist in another?


In [42]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)
#> array([1, 2, 3, 4])

array([1, 2, 3, 4])

# 13. How to get the positions where elements of two arrays match?


In [50]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?

In [ ]:
a = np.arange(15)


In [47]:
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]
print(index)

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([ 5,  6,  7,  8,  9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)


array([ 5,  6,  7,  8,  9, 10])

# 15. How to make a python function that handles scalars to work on numpy arrays?

In [49]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


maxx(1, 5)
#> 5

def pair_maxx(a,b)

5

In [51]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

# 16. How to swap two rows in a 2d numpy array?

In [64]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr.reshape(2,-1)

ValueError: cannot reshape array of size 9 into shape (2,newaxis)

In [65]:
# Solution
arr[:,[1,0,2]]
#> array([[3, 4, 5],
#>        [0, 1, 2],
#>        [6, 7, 8]])

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [67]:
# Solution
arr[[1,2,0], :] # [1,2,0]就是行的顺序，放后面就是列
#> array([[3, 4, 5],
#>        [0, 1, 2],
#>        [6, 7, 8]])

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

# 17. How to swap two columns in a 2d numpy array?

In [69]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 18. How to reverse the rows of a 2D array?


In [75]:
# Input
arr = np.arange(9).reshape(3,3)
print(arr)

# Solution
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19. How to reverse the columns of a 2D array?


In [81]:
# Input
arr = np.arange(9).reshape(3,3)
print(arr)

arr[:,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20. How to create a 2D array containing random floats between 5 and 10?

In [89]:
arr = np.random(5,10)
arr.reshape(5,# Input
arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr= np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)
#> [[ 8.50061025  9.10531502  6.85867783]
#>  [ 9.76262069  9.87717411  7.13466701]
#>  [ 7.48966403  8.33409158  6.16808631]
#>  [ 7.75010551  9.94535696  5.27373226]
#>  [ 8.0850361   5.56165518  7.31244004]]3)

SyntaxError: invalid syntax (<ipython-input-89-70f29c9afa6c>, line 6)

# 21. How to print only 3 decimal places in python numpy array?


In [91]:
rand_arr = np.random.random((5,3))
# Input
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]
#> array([[ 0.443,  0.109,  0.97 ],
#>        [ 0.388,  0.447,  0.191],
#>        [ 0.891,  0.474,  0.212],
#>        [ 0.609,  0.518,  0.403]])

array([[0.541, 0.038, 0.791],
       [0.55 , 0.173, 0.662],
       [0.792, 0.635, 0.764],
       [0.44 , 0.557, 0.333]])

# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [93]:
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [103]:
# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(1001)
rand_arr = np.random.random([3,3])/1e3
rand_arr

np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000306, 0.000265, 0.000196],
       [0.000431, 0.000023, 0.000196],
       [0.000353, 0.000223, 0.000614]])

# 23. How to limit the number of items printed in output of numpy array?